/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiVerifyPaymentRouteImport } from './routes/api/verify-payment'
import { Route as ApiDailyResetRouteImport } from './routes/api/daily-reset'
import { Route as ApiCreateOrderRouteImport } from './routes/api/create-order'
import { Route as ApiAiSmartPaletteRouteImport } from './routes/api/ai/smart-palette'
import { Route as ApiAiLookbookRouteImport } from './routes/api/ai/lookbook'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai/generate'
import { Route as ApiAiEnhancePromptRouteImport } from './routes/api/ai/enhance-prompt'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPaymentRoute = ApiVerifyPaymentRouteImport.update({
  id: '/api/verify-payment',
  path: '/api/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyResetRoute = ApiDailyResetRouteImport.update({
  id: '/api/daily-reset',
  path: '/api/daily-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateOrderRoute = ApiCreateOrderRouteImport.update({
  id: '/api/create-order',
  path: '/api/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSmartPaletteRoute = ApiAiSmartPaletteRouteImport.update({
  id: '/api/ai/smart-palette',
  path: '/api/ai/smart-palette',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiLookbookRoute = ApiAiLookbookRouteImport.update({
  id: '/api/ai/lookbook',
  path: '/api/ai/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiEnhancePromptRoute = ApiAiEnhancePromptRouteImport.update({
  id: '/api/ai/enhance-prompt',
  path: '/api/ai/enhance-prompt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/daily-reset': typeof ApiDailyResetRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/ai/enhance-prompt': typeof ApiAiEnhancePromptRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/ai/lookbook': typeof ApiAiLookbookRoute
  '/api/ai/smart-palette': typeof ApiAiSmartPaletteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/daily-reset': typeof ApiDailyResetRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/ai/enhance-prompt': typeof ApiAiEnhancePromptRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/ai/lookbook': typeof ApiAiLookbookRoute
  '/api/ai/smart-palette': typeof ApiAiSmartPaletteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/daily-reset': typeof ApiDailyResetRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/ai/enhance-prompt': typeof ApiAiEnhancePromptRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/ai/lookbook': typeof ApiAiLookbookRoute
  '/api/ai/smart-palette': typeof ApiAiSmartPaletteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/api/create-order'
    | '/api/daily-reset'
    | '/api/verify-payment'
    | '/auth/callback'
    | '/api/ai/enhance-prompt'
    | '/api/ai/generate'
    | '/api/ai/lookbook'
    | '/api/ai/smart-palette'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/api/create-order'
    | '/api/daily-reset'
    | '/api/verify-payment'
    | '/auth/callback'
    | '/api/ai/enhance-prompt'
    | '/api/ai/generate'
    | '/api/ai/lookbook'
    | '/api/ai/smart-palette'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/api/create-order'
    | '/api/daily-reset'
    | '/api/verify-payment'
    | '/auth/callback'
    | '/api/ai/enhance-prompt'
    | '/api/ai/generate'
    | '/api/ai/lookbook'
    | '/api/ai/smart-palette'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiCreateOrderRoute: typeof ApiCreateOrderRoute
  ApiDailyResetRoute: typeof ApiDailyResetRoute
  ApiVerifyPaymentRoute: typeof ApiVerifyPaymentRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiAiEnhancePromptRoute: typeof ApiAiEnhancePromptRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiAiLookbookRoute: typeof ApiAiLookbookRoute
  ApiAiSmartPaletteRoute: typeof ApiAiSmartPaletteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-payment': {
      id: '/api/verify-payment'
      path: '/api/verify-payment'
      fullPath: '/api/verify-payment'
      preLoaderRoute: typeof ApiVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-reset': {
      id: '/api/daily-reset'
      path: '/api/daily-reset'
      fullPath: '/api/daily-reset'
      preLoaderRoute: typeof ApiDailyResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-order': {
      id: '/api/create-order'
      path: '/api/create-order'
      fullPath: '/api/create-order'
      preLoaderRoute: typeof ApiCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/smart-palette': {
      id: '/api/ai/smart-palette'
      path: '/api/ai/smart-palette'
      fullPath: '/api/ai/smart-palette'
      preLoaderRoute: typeof ApiAiSmartPaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/lookbook': {
      id: '/api/ai/lookbook'
      path: '/api/ai/lookbook'
      fullPath: '/api/ai/lookbook'
      preLoaderRoute: typeof ApiAiLookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/enhance-prompt': {
      id: '/api/ai/enhance-prompt'
      path: '/api/ai/enhance-prompt'
      fullPath: '/api/ai/enhance-prompt'
      preLoaderRoute: typeof ApiAiEnhancePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiCreateOrderRoute: ApiCreateOrderRoute,
  ApiDailyResetRoute: ApiDailyResetRoute,
  ApiVerifyPaymentRoute: ApiVerifyPaymentRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiAiEnhancePromptRoute: ApiAiEnhancePromptRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiAiLookbookRoute: ApiAiLookbookRoute,
  ApiAiSmartPaletteRoute: ApiAiSmartPaletteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
